### ISSUE TITLE
About your evaluation

### ISSUE THREAD

**Issue by Lee-zix** [amy-deng/glean#1]
Dear authors, 
 1. Is the Multi-actore forecasting given the ture label of multi-event or based on the predicted results of the multi-event forecasting task??
2. What are the RE-NET_1, RE-NET_2, RE-NET_3 mean???? The three sub-model in RE-NET?? IN your paper, "RENET 1 directly predicts the events, while RENET 2 follows the logic in the original paper by first predicting the subject and then events." I do not know how RE-NET conduct the multi-event forecasting task.
Thanks very much!

**Comment by amy-deng** [comment]
Sorry for the ambiguity. 
1. Multi-actor forecasting uses the true label of multi-event in my evaluation, since I consider they are separate tasks. 
2. The implementation of RENET: RE-NET1: p(r|G) directly predict events. RE-NET2 p(s|G),p(r|s,G) first predict the subject and then events. RE-NET3: p(s|G) directly predict actors. You may consider they are sub models of RENET.

**Comment by Lee-zix** [comment]
Thank you for your timely reply. I got it!
